### ISSUE TITLE
command hotkeys should be escaped instead of executed

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#45]
cmd+t
cmd+n
cmd+shift+esc
cmd+space
cmd+tab 
cmd+shift+~
cmd+shift+3

hotkeys should be escaped.  Right now they are executed and interfere with the program.

**Comment by KatShambaugh** [comment]
I will look into fixing this!

**Comment by KatShambaugh** [comment]
I have fixed this for a few of the command + key combinations, though some of them it seems like the browser won't let me override the keyboard shortcut.

**Comment by alodahl** [comment]
#118 addresses, but doesnt resolve this issue.  Move it back to 'To do' once #118 is merged.
